export const service_category = [
  "Accounting",
  "Admin",
  "Alterations",
  "Appliances",
  "Architects",
  "Assembly",
  "Audio Visual",
  "Auto Electrician",
  "Bakers",
  "Balloon Delivery",
  "Barbers",
  "Bathroom Renovation",
  "Beauticians",
  "Bicycle Service",
  "Bricklayer",
  "Building & Construction",
  "Business",
  "Cake Delivery",
  "Car Body Work",
  "Car Detailing",
  "Car Inspection",
  "Car Repair",
  "Car Service",
  "Car Wash",
  "Carpentry",
  "Carpet Cleaning",
  "Cat Care",
  "Catering",
  "Chef",
  "Childcare & Safety",
  "Cladding",
  "Cleaning",
  "Clearance Services",
  "Coaching",
  "Coffee Delivery",
  "Commercial Cleaning",
  "Computers & IT",
  "Concreting",
  "Cooking",
  "Counselling & Therapy",
  "Courier Services",
  "Dance Lessons",
  "Decking",
  "Delivery",
  "Design",
  "Dessert Delivery",
  "Dog Care",
  "Draftsman",
  "Driving",
  "Electricians",
  "Electronic Repair",
  "Engraving",
  "Entertainment",
  "Events",
  "Fencing",
  "Fitness",
  "Flooring",
  "Florist",
  "Flower Delivery",
  "Food Delivery",
  "Fresh Food Delivery",
  "Furniture Assembly",
  "Furniture Repair",
  "Gardening",
  "Gate Installation",
  "Gift Delivery",
  "Glaziers",
  "Grocery Delivery",
  "Hair Removal",
  "Hairdressers",
  "Handyman",
  "Health & Wellness",
  "Heating & Cooling",
  "Home & Lifestyle",
  "Home Automation and Security",
  "Home Theatre",
  "House Cleaning",
  "Interior Designer",
  "Kitchen Renovation",
  "Landscaping",
  "Laundry",
  "Lawn Care",
  "Legal Services",
  "Lessons",
  "Local Mobile Mechanic",
  "Locksmith",
  "Makeup Artist",
  "Marketing",
  "Martial Arts",
  "Mechanic",
  "Models",
  "Motorcycle Mechanic",
  "Music Lessons",
  "Painting",
  "Paving",
  "Pest Control",
  "Pet Care",
  "Photographers",
  "Plasterer",
  "Plumbing",
  "Pool Maintenance",
  "Real Estate",
  "Removals",
  "Roofing",
  "Rubbish Removal",
  "Seamstress",
  "Sharpening",
  "Staffing",
  "Surveyors",
  "Swimming Lessons",
  "Tailors",
  "Takeaway & Delivery",
  "Tattoo Artists",
  "Tiling",
  "Tradesman",
  "Translation",
  "Tree Surgeons",
  "Tutoring",
  "Vehicle Transport",
  "Wall Hanging and Mounting",
  "Wallpapering",
  "Waste Collection & Disposal",
  "Waterproofing",
  "Web",
  "Wedding",
  "Wheel & Tyre Service",
  "Window Cleaning",
  "Windows & Doors",
  "Writing",
];
